### ISSUE TITLE
Modifying collections and postponing updates

### ISSUE THREAD

**Issue by macqm** [parse-community/ParseReact#8]
I used Parse SDK before and I could update a property on each model in the collection and when I was sure that I was ready to push the change to the server I would call `save()` method to sync the collection.

For instance, in a list component I used drag and drop to allow to reorder the items. I had created a handler for `dragOver` event that would change _order_ attribute in my models an
a list of items. I also had provided a handler for `dragOver` event that would change _order_ attribute in my models and use `setState(...)` to re-render the list, and a `drop` event handler that would save the collection.

Now that my list of items lives in `this.data` rather than `this.state`, how can I make changes to a particular attribute (e.g. _order_ attribute) of each model in the array and cause re-render, while only sync the list when manipulating with the attributes is finished? Mutations docs or provided in the samples don't seem to cover such a scenario.

**Comment by andrewimm** [comment]
With Mutations, any locally-staged changes need to exist in some component's state. For forms or other similar forms of input, this is usually very simple to handle, but in your case it's obviously a bit more complex. Here's what I would do: have a data component that fetches the results from Parse, and an inner component that receives the results as a `prop`, stores sorting information in its `state`, and handles rendering the items in the currently-staged order.
```jsx
// Vague visualization
<DataComponent>
  <SortingComponent>
    <Item />
    <Item />
    <Item />
  </SortingComponent>
</DataComponent>
```
When you're ready to commit your changes to the server, combine the Parse Objects with that sorting information and construct your Set mutations.

I'm currently working on batching mutations, so that many of them can be executed as a single request (similar to `Object.saveAll()` in the JS SDK), which will probably be helpful to you in this scenario. I'll open an issue so that everyone can follow the progress there.

**Comment by jasecoop** [comment]
@andrewimm Hi Andrew, how did you get on with this batching mutations?

I'm currentl calling 

var batch = ParseReact.Mutation.Batch();

and it returns the following error:

Uncaught TypeError: undefined is not a function

**Comment by andrewimm** [comment]
Are you using v0.4.2? That's when `Batch` was added.

I've been meaning to flesh out the Batch API documentation later today.

**Comment by jasecoop** [comment]
@andrewimm Ah, yes. Update worked.

Looking forward to documentation. Currently a bit lost. I'm trying to loop through an array and update them.

**Comment by andrewimm** [comment]
@jasecoop should be something similar to:

```js
var batch = ParseReact.Mutation.Batch();
this.data.objects.forEach((o) => {
  // Update each object
  ParseReact.Mutation.Set(o, 'foo', 'bar').dispatch({ batch: batch });
});
// Done combining all of the updates, time to send to the server
batch.dispatch();
```
