### ISSUE TITLE
Error with query which include a field which is an array of pointer

### ISSUE THREAD

**Issue by samuelmichaud** [parse-community/ParseReact#91]
Hi,

I have an error when trying to include a field which is an array of pointer.

**Error**

```
ObjectStore.js:59 Uncaught Error: Cannot store an object without an Id
```

**My query**

```
observe: function() {
            return {
                collections: (new Parse.Query('Collection')).include('Requests')
    },
}
```

If tried to debug a bit. I found out that in the storeObject function, data is the array of pointer so it cannot work obviously.

```
function storeObject(data) {
  if (!(data.id instanceof Id)) {
    throw new Error('Cannot store an object without an Id');
  }
  var queries = {};
  if (store[data.id]) {
    queries = store[data.id].queries;
  }
  store[data.id] = { data: data, queries: queries };
  return data.id;
}
```

In this issue: #36, @palamccc (2nd comment) has the same error with also an array of pointer.
The issue #36 was first about another problem so I kept it closed and open this one.

**Nota Bene:** ParseReact v0.4.1 + Parse v1.4.2.

Thank you for your hard work,

**Comment by andrewimm** [comment]
Thanks for providing all of this background information, it helps a lot when debugging. I'll try to investigate this later today.

**Comment by porpdog** [comment]
Hi,
I'm having the same issue with the version you mentioned above and doing an npm update.  I've been trying for some time to use the .include extension with my pointer array and it returns the same error:
var query = (new Parse.Query('Recipe')).include('images');
'Cannot store an object without an Id'

I'm guessing I'm using this wrong because I notice in the ObjectStore, that it's looking directly at the 'data' id, but the data value is, in this case, an array of pointer objects.

Thanks!
Sean

**Comment by jssolichin** [comment]
+1

**Comment by fozzle** [comment]
Having the same issue, using a pointer array and running into the "cannot store an object without an Id" error.

`new Parse.Query('Conversation').include('participants').ascending('createdAt')`

**Comment by fozzle** [comment]
I've just been poking around taking a look at this. I wouldn't mind giving this a shot as I'd really like to be able to include one-many queries in my project.

At risk of stating the obvious:
Flattening the included array of ParseObjects before storing them turns them into an array of 'flattened' Pointer objects rather than 'flattened' ParseObjects. The 'flattened' Pointer objects are missing the 'id' property (which on other flattened ParseObjects, contains an Id object). And so errors are thrown.

So, should flattened Pointer objects have this property?

**Comment by brodynelson** [comment]
I am having this same issue. Is there a workaround in the meantime?

**Comment by spchuang** [comment]
+1

**Comment by Cinezaster** [comment]
+1 Same issue here.

**Comment by dudunato** [comment]
Same issue here, any news?

**Comment by nikkool** [comment]
+1, trying to include and array of pointers to _User

**Comment by ludwigschubert** [comment]
Still an issue I believe. Has anyone got any kind of Many-To-Many relation working at the moment? Am a little confused how this can stay broken for half a year as it seems like core functionality and there's documentation on it? But maybe I'm underestimating how many different SDKs Parse has to maintain…

@andrewimm feel free to let us know if we can help in any way by providing more info/test cases.

**Comment by andrewimm** [comment]
@ludwigschubert we've been trying to get the core JS SDK to the point where there are no new incoming bugs before working to resolve add-on libraries. Now that we're there, I'm committing to dealing with the outstanding issue queue for Parse+React. There will be some major changes in the future as we pivot it towards a collection of libraries that can leverage raw observability and the internals of the JS SDK.

As for this particular issue, I may have an idea as to what's causing it, but I won't have the time to look into it for another few days.

**Comment by ludwigschubert** [comment]
@andrewimm thank you for your response, clarifying and providing a roadmap.
